#!/bin/sh
# Bare Metal Alchemist, 2022

############################################# 
#               Mercury - ☿                 # 
############################################# 

# Toxic, handle with care

# Fixedfloat : I want to use this API, but this is hella proprietary
# Could also use this to connect to dctrl.space as an example

